# scripts that are called at very beginning, before repo cloning
init:
  - git config --global --unset core.autocrlf
# environment variables
environment:
  MAVEN_VERSION: "3.6.3"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk11"
# build cache to preserve files/folders between builds
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2
# scripts that run after cloning repository
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        Write-Host "Downloading Maven $env:MAVEN_VERSION"
        (new-object System.Net.WebClient).DownloadFile("https://downloads.apache.org/maven/maven-3/$env:MAVEN_VERSION/binaries/apache-maven-$env:MAVEN_VERSION-bin.zip", 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET M2_HOME=C:\maven\apache-maven-%MAVEN_VERSION%
  - cmd: SET PATH=%M2_HOME%\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
# to run your custom scripts instead of automatic MSBuild
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# to run your custom scripts instead of automatic tests
test_script:
  - mvn test -B
